source 'https://github.com/CocoaPods/Specs.git'


target 'ResplendentRestkit_Example', :exclusive => true do
  pod "ResplendentRestkit", :path => "../"
end

target 'ResplendentRestkit_Tests', :exclusive => true do
  pod "ResplendentRestkit", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
